apiVersion: v2
name: suse-ai-hr-assistant
description: SUSE AI HR Assistant Demo - Comprehensive LLM Observability with OpenLit and SUSE AI
type: application
version: 0.1.1
appVersion: "latest"
# Dependencies from SUSE Application Collection
dependencies:
  - name: ollama
    version: 1.26.0
    repository: oci://dp.apps.rancher.io/charts
    condition: ollama.enabled
keywords:
  - ai
  - llm
  - observability
  - hr
  - demo
  - openlit
  - ollama
maintainers:
  - name: SUSE AI Team
    email: ai-team@suse.com
home: https://www.suse.com/products/ai/
sources:
  - https://github.com/openlit/openlit
  - https://ollama.ai/
