apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suse-ai-hr-assistant.fullname" . }}-run-script
  labels: 
    {{- include "suse-ai-hr-assistant.labels" . | nindent 4 }}
data:
  run.sh: |-
    #!/bin/sh
    printf "Calling HR Assistant App (${APP_HR_ASSISTANT_URL})\n"
    curl --no-progress-meter "http://${APP_HR_ASSISTANT_URL}:8000/ask"
    printf "\nCalling HR Policy Database App (${APP_HR_POLICY_DB_URL})\n"
    curl --no-progress-meter "http://${APP_HR_POLICY_DB_URL}:8000/ask"
    printf "\nCalling Employee Handbook App (${APP_EMPLOYEE_HANDBOOK_URL})\n"
    curl --no-progress-meter "http://${APP_EMPLOYEE_HANDBOOK_URL}:8000/ask"
    sleep 5
  
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "suse-ai-hr-assistant.fullname" . }}-traffic-generator
  labels: 
    {{- include "suse-ai-hr-assistant.labels" . | nindent 4 }}
spec:
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "suse-ai-hr-assistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: {{ include "suse-ai-hr-assistant.serviceAccountName" . }}
          containers:
          - command:
            - bin/sh
            - -c
            - /app/run.sh
            env:
              - name: APP_HR_ASSISTANT_URL
                value: {{ include "suse-ai-hr-assistant.fullname" . }}-hr-assistant
              - name: APP_HR_POLICY_DB_URL
                value: {{ include "suse-ai-hr-assistant.fullname" . }}-hr-policy-db
              - name: APP_EMPLOYEE_HANDBOOK_URL
                value: {{ include "suse-ai-hr-assistant.fullname" . }}-employee-handbook
            image: badouralix/curl-jq:alpine
            imagePullPolicy: IfNotPresent 
            name: curl
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /app/run.sh
              name: run-script
              subPath: run.sh
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              name: {{ include "suse-ai-hr-assistant.fullname" . }}-run-script
              defaultMode: 0755
            name: run-script
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid