apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suse-ai-hr-assistant.fullname" . }}-hr-assistant
  labels:
    {{- include "suse-ai-hr-assistant.labels" . | nindent 4 }}
    app.component: hr-assistant
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "suse-ai-hr-assistant.selectorLabels" . | nindent 6 }}
      app.component: hr-assistant
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "suse-ai-hr-assistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.component: hr-assistant
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "suse-ai-hr-assistant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: APP_NAME
            value: HRAssistant
          - name: OLLAMA_ENDPOINT
            value: {{ include "suse-ai-hr-assistant.ollamaEndpoint" . }}
          - name: OTLP_ENDPOINT
            value: {{ .Values.otlpEndpoint }}
          - name: COLLECT_GPU_STATS
            value: "{{ .Values.collectGpuStats }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}